#!/sw/installed/Python/3.10.4-GCCcore-11.3.0/bin/python3.10
# -*- coding: utf-8 -*-
import re
import sys
from infer import cli_main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(cli_main())
